import math

# Screen sizing
WIDTH = 1080
HEIGHT = 720
TILE = 100

# Other sizing configuration
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
DOUBLE_WIDTH = 2 * WIDTH
DOUBLE_HEIGHT = 2 * HEIGHT

# FPS Counter
FPS = 60
FPS_POS = (WIDTH - 60, 5)

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (220, 0, 0)
GREEN = (0, 100, 0)
BLUE = (0, 0, 220)
DARKGRAY = (42, 42, 42)
PURPLE = (116, 0, 116)
SKYBLUE = (0, 190, 255)
YELLOW = (222, 222, 0)
SANDY = (242, 162, 94)
DARKBROWN = (100, 64, 26)
DARKORANGE = (252, 138, 0)

# Player
PLAYER_POSITION = (HALF_WIDTH // 4, HALF_HEIGHT - 50)
PLAYER_ANGLE = 0
PLAYER_SPEED = 5
PLAYER_ROTATION_SPEED = 0.02
PLAYER_SENSITIVITY = 0.0038

# Minimap & Map
MAP_FILENAME = "./game/level.txt"
MINIMAP_SCALE = 5
MAP_RESOLUTION = (WIDTH // MINIMAP_SCALE, HEIGHT // MINIMAP_SCALE)
MAP_SCALE = 2 * MINIMAP_SCALE
MAP_TILE = TILE // MAP_SCALE
MAP_POSITION = (0, HEIGHT - HEIGHT // MINIMAP_SCALE)

# Raycaster
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 300
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
DISTANCE = NUM_RAYS / (2 * math.tan(HALF_FOV))
PROJECTION_COEFFICIENT = 3 * DISTANCE * TILE
SCALE = WIDTH // NUM_RAYS

# Sprites
CENTER_RAY = NUM_RAYS // 2 - 1
FAKE_RAYS = 200
FAKE_RAYS_RANGE = NUM_RAYS - 1 + 2 * FAKE_RAYS

# Textures
TEXTURE_WIDTH = 1200
TEXTURE_HEIGHT = 1200
HALF_TEXTURE_HEIGHT = TEXTURE_HEIGHT // 2
TEXTURE_SCALE = TEXTURE_WIDTH // TILE